---
name: Bug Report
description: File a bug report
title: "A Brief Descriptive Title Here"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. Please leave as much detail as possible.
  - type: dropdown
    id: version-project
    attributes:
      label: Project Version
      description: What version of the project are you using?
      options:
        - main (pre-release)
        - 1.0.1 (latest)
        - 1.0.0
    validations:
      required: true
  - type: input
    id: version-vsphere
    attributes:
      label: VMware vSphere
      description: Please provide the VMware vSphere version.
      placeholder: 7.0.3d
    validations:
      required: true
  - type: input
    id: version-packer
    attributes:
      label: HashiCorp Packer
      description: Please provide the HashiCorp Packer version.
      placeholder: 1.9.1
    validations:
      required: true
  - type: textarea
    id: description-details
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: description-steps
    attributes:
      label: Steps to Reproduce:
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "1. Open terminal\n2. Type a command..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
